apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sku-parser-api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: sku-parser.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sku-parser-api
                port:
                  number: 80
